blueprint:
  name: Évènement Flex-D Hydro-Québec
  description: "Automatisation des événements Flex D d'Hydro-Québec pour gérer efficacement les périodes de pointe."
  domain: automation
  input:
    preheat_action:
      name: Actions pour la phase de préchauffage
      description: "à réaliser avant la période critique pour anticiper la pointe, comme ajuster le chauffage ou chauffer l'eau."
      default: []
      selector:
        action: {}
    peak_begin_action:
      name: Actions au début de la pointe
      description: "à exécuter au début de la période de pointe critique pour réduire votre consommation électrique, comme désactiver certains appareils."
      default: []
      selector:
        action: {}
    peak_end_action:
      name: Actions à la fin de la pointe
      description: "à exécuter une fois la période de pointe terminée, pour rétablir vos paramètres habituels."
      default: []
      selector:
        action: {}
mode: parallel
trigger:
- platform: time
  at: sensor.hydropeak_tpc_dpc_preheat_start
  id: pre_heat_trigger
- platform: time
  at: sensor.hydropeak_tpc_dpc_event_start
  id: peak_start_trigger
- platform: time
  at: sensor.hydropeak_tpc_dpc_event_end
  id: peak_end_trigger
action:
- choose:
  - conditions:
    - condition: trigger
      id: pre_heat_trigger
    sequence: !input preheat_action
  - conditions:
    - condition: trigger
      id: peak_start_trigger
    sequence: !input peak_begin_action
  - conditions:
    - condition: trigger
      id: peak_end_trigger
    sequence: !input peak_end_action
